### ISSUE TITLE
3.1系でもCodeceptionのテストが通るようにする

### ISSUE THREAD

**Issue by Yangsin** [EC-CUBE/eccube-codeception#37]
## 概要(Overview)

3.1系でもCodeceptionのテストが通るようにする

## 要望 (Requirement)

- [x] 3.0.14系でも動いていないので動くようにする  
- [x] テストが落ちている箇所の修正 2件 
- [x] 3.1系のシステム要件の下限環境あわせたDockerImageの変更    
    - [x] PostgreSQL  9.2  
    - [x] MySQL 5.5  
- [x] 作成したイメージでのテストの実行

## 関連情報 (Ref)

 なし

**Comment by ryo-endo** [comment]
#161 で新しいIssueを立てたので、こちらCLOSEします。
