### ISSUE TITLE
docker-compose で並列実行

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/eccube-codeception#7]
docker-compose を使えば、もっと簡単に環境を作ることができそう
http://codeception.com/docs/12-ParallelExecution

travis-ci でも実行できそう
https://docs.travis-ci.com/user/docker/
https://github.com/dmstr/docker-yii2-app
https://github.com/dmstr/docker-acception

**Comment by Yangsin** [comment]
#8 で対応ありがとうございます。
